--Create a database called FORMULA_ONE before execution
USE FORMULA_ONE;

CREATE TABLE TEAM(TEAM_ID INT PRIMARY KEY NOT NULL,
 TEAM_NAME VARCHAR(30),
 NO_OF_DRIVERS INT CHECK (NO_OF_DRIVERS<=10),
 NO_OF_PIT_CREW INT CHECK(NO_OF_PIT_CREW<=35),
 NO_OF_CARS INT CHECK(NO_OF_CARS<=5)
);

CREATE TABLE RACE(RACE_ID INT PRIMARY KEY NOT NULL,
NO_OF_LAPS INT CHECK(NO_OF_LAPS<=80),
RACE_DATE DATE,
START_TIME TIME(0),
LOCATION VARCHAR(30)
);

CREATE TABLE CAR(CAR_ID INT NOT NULL,
MODEL VARCHAR(30),
HOURS_DRIVEN INT,
TEAM_ID INT NOT NULL,
PRIMARY KEY (CAR_ID,TEAM_ID),
FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE DRIVER(DRIVER_ID INT NOT NULL,
NAME VARCHAR(30),
DOB DATE,
CAR_ID INT NOT NULL,
TEAM_ID INT NOT NULL,
PRIMARY KEY (DRIVER_ID,TEAM_ID),
FOREIGN KEY (CAR_ID) REFERENCES CAR(CAR_ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PIT_CREW_MEMBER(MEMBER_ID INT NOT NULL,
DOB DATE,
NAME VARCHAR(30),
TEAM_ID INT NOT NULL,
JOINED_ON DATE,
PRIMARY KEY (MEMBER_ID,TEAM_ID),
FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TRIGGER DRIVER_ADD
AFTER INSERT ON DRIVER
FOR EACH ROW
   UPDATE TEAM
   SET NO_OF_DRIVERS=NO_OF_DRIVERS+1
   WHERE TEAM_ID=NEW.TEAM_ID;

CREATE TRIGGER DRIVER_DEL
AFTER DELETE ON DRIVER
FOR EACH ROW
   UPDATE TEAM
   SET NO_OF_DRIVERS=NO_OF_DRIVERS-1
   WHERE TEAM_ID=OLD.TEAM_ID;

CREATE TRIGGER CAR_ADD
AFTER INSERT ON CAR
FOR EACH ROW
   UPDATE TEAM
   SET NO_OF_CARS=NO_OF_CARS+1
   WHERE TEAM_ID=NEW.TEAM_ID;

CREATE TRIGGER CAR_DEL
AFTER DELETE ON CAR
FOR EACH ROW
   UPDATE TEAM
   SET NO_OF_CARS=NO_OF_CARS-1
   WHERE TEAM_ID=OLD.TEAM_ID;

CREATE TRIGGER CREW_ADD
AFTER INSERT ON PIT_CREW_MEMBER
FOR EACH ROW
   UPDATE TEAM
   SET NO_OF_PIT_CREW=NO_OF_PIT_CREW+1
   WHERE TEAM_ID=NEW.TEAM_ID;

CREATE TRIGGER CREW_DEL
AFTER DELETE ON PIT_CREW_MEMBER
FOR EACH ROW
   UPDATE TEAM
   SET NO_OF_PIT_CREW=NO_OF_PIT_CREW-1
   WHERE TEAM_ID=OLD.TEAM_ID;

DELIMITER $$

CREATE TRIGGER DRIVER_TEAM_CHANGE
AFTER UPDATE ON DRIVER
FOR EACH ROW
BEGIN
  UPDATE TEAM SET NO_OF_DRIVERS=NO_OF_DRIVERS-1 WHERE TEAM_ID=OLD.TEAM_ID;
  UPDATE TEAM SET NO_OF_DRIVERS=NO_OF_DRIVERS+1 WHERE TEAM_ID=NEW.TEAM_ID;
END$$

CREATE TRIGGER PIT_CREW_TEAM_CHANGE
AFTER UPDATE ON PIT_CREW_MEMBER
FOR EACH ROW
BEGIN
  UPDATE TEAM SET NO_OF_PIT_CREW=NO_OF_PIT_CREW-1 WHERE TEAM_ID=OLD.TEAM_ID;
  UPDATE TEAM SET NO_OF_PIT_CREW=NO_OF_PIT_CREW+1 WHERE TEAM_ID=NEW.TEAM_ID;
END$$

DELIMITER ;

CREATE TABLE PARTICIPATES_IN(TEAM_ID INT NOT NULL,
RACE_ID INT NOT NULL,
POSITION INT,
PRIMARY KEY (TEAM_ID, RACE_ID),
CONSTRAINT RACE1 UNIQUE(RACE_ID,POSITION),
FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (RACE_ID) REFERENCES RACE(RACE_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PIT_CREW_CARS_WORKED_ON(MEMBER_ID INT NOT NULL,
CAR_ID INT NOT NULL,
PRIMARY KEY (MEMBER_ID,CAR_ID),
FOREIGN KEY (MEMBER_ID) REFERENCES PIT_CREW_MEMBER(MEMBER_ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (CAR_ID) REFERENCES CAR(CAR_ID) ON DELETE CASCADE ON UPDATE CASCADE
);
